name: MKP-Build-Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  # ////////////////////////////////////////////////////////////////////////

  build:
    name: Build MKP
    runs-on: ubuntu-latest
    container:
      image: checkmk/check-mk-raw:2.1.0-latest
    env:
      OMD_ROOT: /omd/sites/cmk
      OMD_SITE: cmk
      CMK_SITE_ID: cmk
      WORKSPACE: ${{ github.workspace }}

    steps:
      - name: Install packages
        run: apt update && apt-get -y install jq tree
      - name: Create Checkmk Site
        run: /docker-entrypoint.sh /bin/true
      - name: Checkout project repository
        uses: actions/checkout@v3
      - name: Link repository files into container
        run: .devcontainer/linkfiles.sh
      - name: Update GITHUB_PATH
        run: echo "/omd/sites/cmk/bin" >> $GITHUB_PATH
      - name: Execute build script
        run: .devcontainer/build.sh
        id: cmkpkg
      - name: Upload MKP artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.cmkpkg.outputs.pkgfile }}
          path: ${{ steps.cmkpkg.outputs.pkgfile }}

  # ////////////////////////////////////////////////////////////////////////

  # https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts#downloading-or-deleting-artifacts
  release:
    name: Release MKP
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      WORKSPACE: ${{ github.workspace }}
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v3
      - name: Download MKP artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.cmkpkg.outputs.pkgfile }}
          # download dir
          path: mkp

      - name: Debug - Show downloaded content
        run: ls -la mkp/*
      - name: Show ref
        run: echo ${GITHUB_REF##*/}
      - name: Download chag tool
        uses: wei/curl@master
        with:
          args: https://raw.githubusercontent.com/mtdowling/chag/master/chag --output chag
      - name: chag
        run: bash chag contents > RELEASE_CHANGELOG.md

      - name: Get Tag
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/}

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      # The Release text will be taken from the annotated tag, created with "chag", see Ref xBCjym
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${GITHUB_REF##*/}
        with:
          name: Release ${{ steps.tag.outputs.VERSION }}
          body_path: RELEASE_CHANGELOG.md
          draft: false
          prerelease: false

      # -m "" means: Leave the Release mesage body as it is, do not modify
      - name: Add Release Assets
        run: hub release edit $(find mkp/ -type f -name "*.mkp" -printf "-a %p ") -m "" "${GITHUB_REF#refs/*/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
